/*
 * Browser-side configuration.
 *
 * GENERATED from config.py by tools/make_page_config.py.
 * Do not edit this file by hand -- edit config.py (or set DSH_* environment
 * variables) and regenerate:
 *
 *     python3 tools/make_page_config.py
 *
 * The page works without this file: every value falls back to a built-in
 * default, so a plain `python3 -m http.server` in a fresh checkout still
 * behaves exactly as before.
 */
window.DSH_CONFIG = {
    "signalingPort": 8765,
    "iceServers": [
        {
            "urls": "stun:stun.l.google.com:19302"
        },
        {
            "urls": "stun:stun.miwifi.com:3478"
        }
    ]
};
