#!/usr/bin/env python3
"""
Regenerate config.js (the browser page's configuration) from config.py.

The browser cannot import Python, so the few values the page needs are copied
into a JavaScript file.  This keeps config.py the single place to edit.

    python3 tools/make_page_config.py            # write config.js
    python3 tools/make_page_config.py --check    # fail if it is out of date

--check is intended for a pre-commit or CI step: it catches the case where
config.py was edited but config.js was not regenerated, which would otherwise
show up as a page that silently uses stale settings.
"""

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import config  # noqa: E402  (path set up above)

OUTPUT = ROOT / "config.js"

HEADER = """/*
 * Browser-side configuration.
 *
 * GENERATED from config.py by tools/make_page_config.py.
 * Do not edit this file by hand -- edit config.py (or set DSH_* environment
 * variables) and regenerate:
 *
 *     python3 tools/make_page_config.py
 *
 * The page works without this file: every value falls back to a built-in
 * default, so a plain `python3 -m http.server` in a fresh checkout still
 * behaves exactly as before.
 */
window.DSH_CONFIG = """


def render():
    payload = {
        "signalingPort": config.SIGNALING_PORT,
        "iceServers": config.ice_servers(),
    }
    body = json.dumps(payload, indent=4, ensure_ascii=False)
    return HEADER + body + ";\n"


def main():
    rendered = render()
    check_only = "--check" in sys.argv

    if check_only:
        if not OUTPUT.exists():
            print("FAIL: config.js does not exist; run tools/make_page_config.py")
            return 1
        if OUTPUT.read_text(encoding="utf-8") != rendered:
            print("FAIL: config.js is out of date with config.py")
            print("      run: python3 tools/make_page_config.py")
            return 1
        print("OK   config.js matches config.py")
        return 0

    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"OK   wrote {OUTPUT}")
    print(f"     signalling port : {config.SIGNALING_PORT}")
    print(f"     ice servers     : {config.ice_servers()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
